<a href="https://colab.research.google.com/github/Harshavardhan2006/23CSBTB27-28/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creation Array and Array Operation


In [1]:
import numpy as np
arry = np.array([2,5,3,7,3])
print(arry)
print(type(arry))

[2 5 3 7 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arry1 = np.array({'apple','banana','orange'})
print(arry1)
print(type(arry1))

{'apple', 'orange', 'banana'}
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arry = np.array([[2,5],[4,2]])
arry1 = np.array([[2,5,4,2],[4,2,1,0]])
arry2 = np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)

[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [4]:
import numpy as np
arry1 = np.array([1,3,4,5,6])
arry2 = np.array([2,6,3,4,8])
print(arry1)
print(arry2)
print(np.add(arry1,arry2))
print(type(arry1))

[1 3 4 5 6]
[2 6 3 4 8]
[ 3  9  7  9 14]
<class 'numpy.ndarray'>
